[project]
name = "langgraph-tutorial"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.140.7",
    "ipykernel>=7.3.0",
    "langchain-groq>=1.1.3",
    "langchain-mcp-adapters>=0.3.0",
    "langchain-openai>=1.3.5",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.9",
    "openai>=2.45.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "sse-starlette>=3.4.6",
    "uvicorn>=0.51.0",
    "winappdbg>=1.5",
]
